### ISSUE TITLE
Stack Prefetch does not seem to work when you switch series

### ISSUE THREAD

**Issue by chafey** [chafey/cornerstoneTools#7] opened 2014-10-23 13:37 UTC
Reported by Rafael Faria Schedit

Steps to reproduce:
1) Go to cornerstoneDemo site
2) Open Mister, MR
3) Open network window in chrome
4) clear newtwork window
5) Select series #2 (Sag T1)
6) Immediately start scrolling the mouse

Observed: Stack prefetch does not occur (check network window in chrome)

Expected: Stack prefetch should occur on Sag T1 window

**Comment by swederik** [comment] 2015-05-11 21:39
Might be fixed by #38

**Comment by swederik** [comment] 2015-06-14 11:59
Closing since I can't reproduce this.

**Closed by swederik** 2015-06-14 11:59 UTC
